trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs: 
    command: test
    projects: 'myWebTest/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: Docker@2
  inputs:
    containerRegistry: 'bazarConnection'
    repository: 'bazarRepo'
    command: 'buildAndPush'
    Dockerfile: 'myweb/Dockerfile'