
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  buildConfiguration: 'Release'
steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'myweb/myweb.csproj'


- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    workingDirectory: 'myweb/'
    arguments: '--configuration $(buildConfiguration)'



- task: Docker@2
  inputs:
    containerRegistry: 'bazarConnection'
    repository: 'bazarRepo'
    command: 'buildAndPush'
    Dockerfile: 'myweb/Dockerfile'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'backend'
    publishLocation: 'Container'