
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  buildConfiguration: 'Release'
  tag: $('Build.BuildId')
stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImage)
    steps:
    - task: DotNetCoreCLI@2
      inputs: 
        command: test
        projects: '/myWebTest/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: bazar
        dockerfile: myweb/Dockerfile
        containerRegistry: 'bazarConnection'
        tags: |
          $(tag)
  

